### ISSUE TITLE
Add entry - Harvest Moon 3D - The Lost Valley (USA)

### ISSUE THREAD

**Issue by ghost** [libretro-thumbnails/Nintendo_-_Nintendo_3DS#21]
![Harvest Moon 3D - The Lost Valley (USA)](https://user-images.githubusercontent.com/105944840/170148212-d12243b1-2ae9-4b3f-834d-47483a9c82a1.png)

**Comment by RobLoach** [comment]
Would you mind submitting these as pull requests instead?

**Comment by ghost** [comment]
I'll look into how to do that. I have little to no idea what I'm doing on here for now. Did you see the stuff on the DS side of it where changes that have been committed aren't being picked up by the per game "Download thumbnail" option? Any idea what's going on with that?
