### ISSUE TITLE
Not sure what these are

### ISSUE THREAD

**Issue by ghost** [libretro-thumbnails/Nintendo_-_Nintendo_3DS#37]
I'm not sure what these are, but can I just delete them and replace the entries/names with actual pngs?
<img width="535" alt="image" src="https://user-images.githubusercontent.com/105944840/170406508-6ce627cf-7ffb-4111-9ea0-e3a5f16a7d51.png">
<img width="421" alt="image" src="https://user-images.githubusercontent.com/105944840/170406545-fce0fd04-85ea-466a-962d-dd838ffdf688.png">
<img width="458" alt="image" src="https://user-images.githubusercontent.com/105944840/170406564-fbcc0bb7-50b4-42a7-82c7-909e344029e3.png">
<img width="583" alt="image" src="https://user-images.githubusercontent.com/105944840/170406603-a6b7b689-954a-41c9-bbee-47342ebd1513.png">
<img width="541" alt="image" src="https://user-images.githubusercontent.com/105944840/170406627-215c5d27-315f-4ab7-98c7-e9caf12738e2.png">

**Comment by RobLoach** [comment]
Those are symbolic links. They point to another file. In the case of `Pokemon Omega Ruby (USA) (En,Ja,Fr,De,Es,It,Ko) (Rev 2).png`, it will reference `Pokemon Omega Ruby (USA) (En,Ja,Fr,De,Es,It,Ko).png`. On systems that support symlinks, it saves file space.

**Comment by ghost** [comment]
Ah, I see it now. Thanks

**Comment by ghost** [comment]
Any simple way of explaining how to create these? I'm trying to look it up and it seems like it's way more complicated than it needs to be. I'm expecting "create new file" then some kind of command followed by the file it's referencing. Is it worthwhile to try and go through and replace files with these symbolic links, most likely (USA) -> (Rev#) ?

**Comment by RobLoach** [comment]
There are some GUIs for it, depending on your platform. For Mac or Linux it's with `ln -sf`.
